apiVersion: v1
kind: Service
metadata:
  name: Service Name
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31000 # optional to specify
